### ISSUE TITLE
Please correct a specific link

### ISSUE THREAD

**Issue by t2informatik** [TeamTopologies/Team-Topologies-Community-Materials#12]
Could you please change the link https://t2informatik.de/en/blog/processes-methods/team-topologies-in-adaptive-organisations/?noredirect=en-US to https://t2informatik.de/en/blog/processes-methods/team-topologies-in-adaptive-organisations/ ...

There's no need for a redirect from the German site.

Cheers, Michael

**Comment by matthewskelton** [comment]
Thank you - Done
